method = 'AlphaDesign'
hidden_dim = 128
node_features = 128
edge_features = 128
k_neighbors = 30
dropout = 0.1
att_output_mlp = True
node_output_mlp = True
num_encoder_layers = 10
use_SGT = True
use_new_feat = True
use_NAT = True
AT_layer_num = 3
autoregressive = 0
batch_size = 8
lr = 0.001
patience = 100
epoch=100