method = 'PiFold'
hidden_dim = 128
node_features = 128
edge_features = 128
k_neighbors = 30
dropout = 0.1
num_encoder_layers = 10
Ca_Ca = 1
Ca_C = 1
Ca_N = 1
Ca_O = 1
C_C = 1
C_N = 1
C_O = 1
N_N = 1
N_O = 1
O_O = 1
updating_edges = 4
node_dist = 1
node_angle = 1
node_direct = 1
edge_dist = 1
edge_angle = 1
edge_direct = 1
virtual_num = 3
att_output_mlp = True
node_output_mlp = True
dihedral_type = 0
NAT = 3
node_net ='AttMLP'
edge_net = 'EdgeMLP'
node_context = 1
edge_context = 0
autoregressive = 0
AT_layer_num = 3
use_gvp_feat = 0
num_decoder_layers1 =3 
kernel_size1 =3 
act_type ='silu'
num_decoder_layers2 = 3
kernel_size2 = 3
glu = 0
epoch=20
batch_size = 8
lr = 0.001
patience = 100